config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :member do
    get "/", to: "pages#dashboard"
    get :calendar, to: "pages#calendar"
    get :roster, to: "pages#roster"

    resources :users do
      put :stop_acting, on: :collection
      put :act_as, on: :member
    end
    
    resources :characters
    resources :calendar_events do
      get :preview, on: :member
    end

    resources :event_participations
  end

  root to: 'pages#index'

end

app/models/character.rb
class Character
  include Mongoid::Document
  include Mongoid::Slug


  field :playable_class
  field :spec

  field :name
  slug :name

  field :level, type: Integer, default: 60
  field :primary_professions, type: Array, default: ->{[]}
  field :secondary_professions, type: Array, default: ->{[]}
  field :main, type: Boolean, default: true
  field :officer_note, default: ""
  field :class_master, type: Boolean, default: false


  belongs_to :user
  has_many :event_participations, dependent: :destroy
  has_many :histories, as: :subject

  before_save :sanitize_professions
  before_create :ensure_main
  before_save :ensure_main_uniqueness



  def class_and_spec
    "#{playable_class}_#{spec}"
  end

  def role
    Character.role_for class_and_spec
  end


  def self.role_for class_and_spec
    roles = {
      warrior_protection: "tank",
      warrior_arms: "melee",
      warrior_fury: "melee",
      druid_guardian: "tank",
      druid_feral: "melee",
      druid_restoration: "healer",
      druid_balance: "range",
      hunter_marksmanship: "range",
      hunter_beastmastery: "range",
      hunter_survival: "range",
      warlock_destruction: "range",
      warlock_affliction: "range",
      warlock_demonology: "range",
      shaman_enhancement: "melee",
      shaman_elemental: "range",
      shaman_restoration: "healer",
      priest_holy: "healer",
      priest_discipline: "healer",
      priest_shadow: "range",
      rogue_assassination: "melee",
      rogue_combat: "melee",
      rogue_subtelty: "melee",
      mage_arcane: "range",
      mage_fire: "range",
      mage_frost: "range"
    }
    roles[class_and_spec.to_sym]
  end


  private


  def sanitize_professions
    self.primary_professions = primary_professions.select{|p| !p.blank? }
    self.secondary_professions = secondary_professions.select{|p| !p.blank? }
  end


  def ensure_main
    unless user.has_character?
      self.main = true
    end
  end


  def ensure_main_uniqueness
    if main_changed? && main
      user.characters.each do |character|
        if character != self
          character.main = false
          character.save!
        end
      end
    end
  end




end

app/controllers/member/calendar_events_controller.rb
module Member

  class CalendarEventsController < MemberController

    before_action :get_calendar_event, only: [:edit, :update, :destroy, :show, :preview]
    before_action :check_permissions, only: [:new, :create, :edit, :update, :destroy]


    def index
      @calendar_events = CalendarEvent.all

      respond_to do |format|
        format.json {
          render json: @calendar_events.map(&:for_fullcalendar)
        }
      end
    end


    def new
      @calendar_event = CalendarEvent.new
      if params[:date]
        @calendar_event.date = params[:date].to_datetime + 21.hours
      end
    end


    def create
      @calendar_event = CalendarEvent.new(calendar_event_params)
      @calendar_event.user = current_user
      @calendar_event.save!
      redirect_to member_calendar_path
    end


    def show
      @event_participation = @calendar_event.user_participation(current_user)
    end


    def preview
      @event_participation = @calendar_event.user_participation(current_user)

      render layout: false
    end


    def edit
    end


    def update
      if params[:start] == "true"
        @calendar_event.start!
      else
        @calendar_event.update(calendar_event_params)
      end
      redirect_to member_calendar_event_path
    end


    def destroy
      @calendar_event.destroy
      redirect_to member_calendar_path
    end


    private


    def get_calendar_event
      @calendar_event = CalendarEvent.find(params[:id])
    end


    def calendar_event_params
      params[:calendar_event] ||= {}
      params[:calendar_event].permit(:name, :date, :description, :raid)
    end


    def check_permissions
      render_401 unless current_user.officer?
    end

  end
  
end

app/controllers/member/characters_controller.rb
module Member

  class CharactersController < MemberController

    before_action :get_character, only: [:edit, :update, :destroy, :show]
    before_action :check_permissions, only: [:edit, :update, :destroy]


    def index
      @characters = Character.all
    end


    def new
      @character = Character.new
    end


    def create
      @character = Character.new(character_params)
      @character.user = current_user
      @character.save!
      redirect_to member_characters_path
    end


    def edit
    end


    def update
      @character.update!(character_params)
      redirect_to member_characters_path
    end


    def destroy
      @character.destroy
      redirect_to member_characters_path
    end


    def show
      @histories = @character.histories.desc(:created_at).limit(10)
    end


    private


    def character_params
      params[:character].permit(:name, :playable_class, :level, :spec, :main, :officer_note, :class_master, :primary_professions => [], :secondary_professions => [])
    end


    def get_character
      @character = Character.find(params[:id])
    end


    def check_permissions
      render_401 unless current_user.can_edit_character? @character
    end

    
  end
  
end

app/controllers/member/event_participations_controller.rb
module Member

  class EventParticipationsController < MemberController

    before_action :get_event_participation, only: [:update]
    before_action :check_character_ownership, only: [:update]
    before_action :check_calendar_event, only: [:update]
    
    def create
      @event_participation = EventParticipation.new(event_participation_params)
      check_character_ownership
      check_calendar_event

      @event_participation.updated_by = current_user
      @event_participation.save!
      redirect_to member_calendar_event_path(@event_participation.calendar_event.id)
    end


    def update
      @event_participation.updated_by = current_user
      @event_participation.update!(event_participation_params)
      redirect_to member_calendar_event_path(@event_participation.calendar_event.id)
    end


    private


    def get_event_participation
      @event_participation = EventParticipation.find(params[:id])
    end


    def event_participation_params
      allowed = [:calendar_event_id, :character_id, :presence]
      allowed << :status if current_user.officer?
      params[:event_participation].permit(allowed)
    end


    def check_character_ownership
      character = @event_participation.character
      render_401 unless current_user.officer? || (character && character.user == current_user)
    end


    def check_calendar_event
      calendar_event = @event_participation.calendar_event
      render_401 unless current_user.officer? || (calendar_event && !calendar_event.started?)
    end

    
  end

end

app/controllers/member/pages_controller.rb
module Member

  class PagesController < MemberController

    def dashboard
      @calendar_events = CalendarEvent.where(:date.gte => DateTime.now - 6.hours, :date.lte => DateTime.now + 2.weeks).asc(:date)
    end


    def calendar
    end


    def roster
      @characters = Character.all
    end

  end

end

app/controllers/member/users_controller.rb
module Member

  class UsersController < MemberController

    before_action :get_user, only: [:edit, :update, :destroy, :show, :act_as]
    before_action :check_permissions, only: [:edit, :update, :destroy]


    def index
      @users = User.all
    end


    def edit
    end


    def update
      user_params[:rank] = @user.rank if user_params[:rank] == "guild_master"
      @user.update(user_params)

      redirect_to member_user_path @user
    end


    def destroy
      @user.destroy
      redirect_to member_users_path
    end


    def show
    end


    def act_as
      if real_current_user.can_act_as?(@user)
        session[:acting_as_user_id] = params[:id]
        redirect_to request.referer || member_users_url
      else
        render_401
      end
    end


    def stop_acting
      session[:acting_as_user_id] = nil
      redirect_to request.referer || member_users_url
    end


    private


    def user_params
      allowed = [:email, :nickname]
      allowed << :rank if current_user.officer?
      params[:user].permit(allowed)
    end


    def get_user
      @user = User.find(params[:id])
    end


    def check_permissions
      render_401 unless current_user.can_edit_user? @user
    end


  end
  
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  before_action :authenticate_user!
  layout "member"
end

app/views/member/characters/_character.html.erb
<%= link_to member_character_path(character), class: "character-card" do %>
    <div class="character-card-info<%= ' main-character' if character.main %>">
        <div class="character-card-level"><%= character.level %></div>
        <div class="character-card-name"><%= character.name %></div>
        <span class="character-card-class"><%= t "playable_classes." + character.playable_class %></span>
        <span class="character-card-class"><%= t "specs." + character.playable_class + "." + character.spec %></span>
    </div>
    <div class="character-card-crest <%= character.playable_class %>"></div>
<% end %>

app/views/member/characters/_form.html.erb
<%= form_for [:member, character], html: {class: "form"} do |f| %>

    <div class="form-group">
        <%= f.label :name, "Nom :" %>
        <%= f.text_field :name, class: "text-field" %>
    </div>

    <div class="form-group character-class">
        <%= f.label :playable_class, "Classe :" %>
        <%= f.select :playable_class, options_for_select(playable_class_labels, character.playable_class), {include_blank: true}, {class: "select"} %>
    </div>


    <div class="form-group character-spec" data-spec="<%= character.spec %>">
        <%= f.label :spec, "Spécialisation :" %>
        <%= f.select :spec, options_for_select({}), {}, {class: "select"} %>
    </div>

    <div class="form-group">
        <%= f.label :level, "Niveau :" %>
        <%= f.number_field :level, class: "text-field" %>
    </div>

    <div class="form-group professions-container">
        <%= f.label :primary_professions, "Métiers principaux :" %>
        <%= f.select :primary_professions, options_for_select(primary_professions_labels, character.primary_professions), {}, {multiple: true, class: "professions-select"} %>
    </div>

    <div class="form-group professions-container">
        <%= f.label :secondary_professions, "Métiers secondaires :" %>
        <%= f.select :secondary_professions, options_for_select(secondary_professions_labels, character.secondary_professions), {}, {multiple: true, class: "professions-select"} %>
    </div>

    <div class="form-group checkbox-container">
        <%= f.label :main, "Personnage principal :" %>
        <%= f.check_box(:main) %>
    </div>

    <div class="form-group checkbox-container">
        <%= f.label :class_master, "Maître de classe :" %>
        <%= f.check_box(:class_master) %>
    </div>

    <div class="form-group officer-note">
        <%= f.label :officer_note, "Notes des officiers :" %>
        <%= f.text_area :officer_note %>
    </div>

    <div class="form-actions">
        <%= f.submit class:"button" %>
    </div>

<% end %>

app/views/member/characters/edit.html.erb
<h1>Editer le personnage</h1>

<div class="page-actions">
    <%= link_to "Supprimer", member_character_path(@character), class: "button", method: :delete, data: {confirm: "Confirmer la suppression"} %>
</div>

<%= render "form", character: @character %>

app/views/member/characters/index.html.erb
<h1>Roster</h1>


<table id="characters" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Level</th>
            <th>Class</th>
            <th>Spec.</th>
            <th>Metiers</th>
        </tr>
    </thead>
    <tbody>
        <% @characters.each do |character| %>
            <tr>
                <td><%= link_to character.name, member_character_path(character), class: character.playable_class %></td>
                <td><%= character.level %></td>
                <td>
                    <span class="hidden"><%= t "playable_classes." + character.playable_class %></span>
                    <div class="wow-icon <%= character.playable_class %>"></div>
                </td>
                <td>
                    <span class="hidden">
                        <%= t "specs." + character.playable_class + "." + character.spec %>
                    </span>
                    <div class="wow-icon <%= character.playable_class %>-<%= character.spec %>"></div>
                </td>
                <td>
                    <span class="hidden">
                        <%= translated_professions character %>
                    </span>
                    <% character.primary_professions.each do |profession| %>
                        <div class="wow-icon <%= profession %>" title="<%= t "primary_professions." + profession %>"></div>
                    <% end %>
                    <% character.secondary_professions.each do |profession| %>
                        <div class="wow-icon <%= profession %>" title="<%= t "secondary_professions." + profession %>"></div>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/member/characters/new.html.erb
<h1>Nouveau personnage</h1>
<%= render "form", character: @character %>

app/views/member/characters/show.html.erb
<h1 class="<%= @character.playable_class %>"><%= @character.name %></h1>

<% if current_user.can_edit_character? @character %>
    <div class="page-actions">
        <%= link_to "Editer", edit_member_character_path(@character), class: 'button' %>
    </div>
<% end %>


<div class="character-show-crest <%= @character.playable_class %>">
    <div class="character-show-level <%= @character.playable_class %>"><%= @character.level %></div>
    <div class="character-show-class <%= @character.playable_class %>"><div class="wow-icon <%= @character.playable_class %>-<%= @character.spec %>"></div></div>
</div>


<div class="character-show-professions">
    <% @character.primary_professions.each do |profession| %>
        <div class="wow-icon <%= profession %>"></div>
    <% end %>

    <% @character.secondary_professions.each do |profession| %>
        <div class="wow-icon <%= profession %>"></div>
    <% end %>
</div>

<div class="feed">
    <%= render @histories %>
</div>