config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :member do
    get "/", to: "pages#dashboard"
    get :calendar, to: "pages#calendar"
    get :roster, to: "pages#roster"

    resources :users do
      put :stop_acting, on: :collection
      put :act_as, on: :member
    end
    
    resources :characters
    resources :calendar_events do
      get :preview, on: :member
    end

    resources :event_participations
  end

  root to: 'pages#index'

end

app/controllers/member/calendar_events_controller.rb
module Member

  class CalendarEventsController < MemberController

    before_action :get_calendar_event, only: [:edit, :update, :destroy, :show, :preview]
    before_action :check_permissions, only: [:new, :create, :edit, :update, :destroy]


    def index
      @calendar_events = CalendarEvent.all

      respond_to do |format|
        format.json {
          render json: @calendar_events.map(&:for_fullcalendar)
        }
      end
    end


    def new
      @calendar_event = CalendarEvent.new
      if params[:date]
        @calendar_event.date = params[:date].to_datetime + 21.hours
      end
    end


    def create
      @calendar_event = CalendarEvent.new(calendar_event_params)
      @calendar_event.user = current_user
      @calendar_event.save!
      redirect_to member_calendar_path
    end


    def show
      @event_participation = @calendar_event.user_participation(current_user)
    end


    def preview
      @event_participation = @calendar_event.user_participation(current_user)

      render layout: false
    end


    def edit
    end


    def update
      if params[:start] == "true"
        @calendar_event.start!
      else
        @calendar_event.update(calendar_event_params)
      end
      redirect_to member_calendar_event_path
    end


    def destroy
      @calendar_event.destroy
      redirect_to member_calendar_path
    end


    private


    def get_calendar_event
      @calendar_event = CalendarEvent.find(params[:id])
    end


    def calendar_event_params
      params[:calendar_event] ||= {}
      params[:calendar_event].permit(:name, :date, :description, :raid)
    end


    def check_permissions
      render_401 unless current_user.officer?
    end

  end
  
end

app/controllers/member/characters_controller.rb
module Member

  class CharactersController < MemberController

    before_action :get_character, only: [:edit, :update, :destroy, :show]
    before_action :check_permissions, only: [:edit, :update, :destroy]


    def index
      @characters = Character.all
    end


    def new
      @character = Character.new
    end


    def create
      @character = Character.new(character_params)
      @character.user = current_user
      @character.save!
      redirect_to member_characters_path
    end


    def edit
    end


    def update
      @character.update!(character_params)
      redirect_to member_characters_path
    end


    def destroy
      @character.destroy
      redirect_to member_characters_path
    end


    def show
      @histories = @character.histories.desc(:created_at).limit(10)
    end


    private


    def character_params
      params[:character].permit(:name, :playable_class, :level, :spec, :main, :officer_note, :class_master, :primary_professions => [], :secondary_professions => [])
    end


    def get_character
      @character = Character.find(params[:id])
    end


    def check_permissions
      render_401 unless current_user.can_edit_character? @character
    end

    
  end
  
end

app/controllers/member/event_participations_controller.rb
module Member

  class EventParticipationsController < MemberController

    before_action :get_event_participation, only: [:update]
    before_action :check_character_ownership, only: [:update]
    before_action :check_calendar_event, only: [:update]
    
    def create
      @event_participation = EventParticipation.new(event_participation_params)
      check_character_ownership
      check_calendar_event

      @event_participation.updated_by = current_user
      @event_participation.save!
      redirect_to member_calendar_event_path(@event_participation.calendar_event.id)
    end


    def update
      @event_participation.updated_by = current_user
      @event_participation.update!(event_participation_params)
      redirect_to member_calendar_event_path(@event_participation.calendar_event.id)
    end


    private


    def get_event_participation
      @event_participation = EventParticipation.find(params[:id])
    end


    def event_participation_params
      allowed = [:calendar_event_id, :character_id, :presence]
      allowed << :status if current_user.officer?
      params[:event_participation].permit(allowed)
    end


    def check_character_ownership
      character = @event_participation.character
      render_401 unless current_user.officer? || (character && character.user == current_user)
    end


    def check_calendar_event
      calendar_event = @event_participation.calendar_event
      render_401 unless current_user.officer? || (calendar_event && !calendar_event.started?)
    end

    
  end

end

app/controllers/member/pages_controller.rb
module Member

  class PagesController < MemberController

    def dashboard
      @calendar_events = CalendarEvent.where(:date.gte => DateTime.now - 6.hours, :date.lte => DateTime.now + 2.weeks).asc(:date)
    end


    def calendar
    end


    def roster
      @characters = Character.all
    end

  end

end

app/controllers/member/users_controller.rb
module Member

  class UsersController < MemberController

    before_action :get_user, only: [:edit, :update, :destroy, :show, :act_as]
    before_action :check_permissions, only: [:edit, :update, :destroy]


    def index
      @users = User.all
    end


    def edit
    end


    def update
      user_params[:rank] = @user.rank if user_params[:rank] == "guild_master"
      @user.update(user_params)

      redirect_to member_user_path @user
    end


    def destroy
      @user.destroy
      redirect_to member_users_path
    end


    def show
    end


    def act_as
      if real_current_user.can_act_as?(@user)
        session[:acting_as_user_id] = params[:id]
        redirect_to request.referer || member_users_url
      else
        render_401
      end
    end


    def stop_acting
      session[:acting_as_user_id] = nil
      redirect_to request.referer || member_users_url
    end


    private


    def user_params
      allowed = [:email, :nickname]
      allowed << :rank if current_user.officer?
      params[:user].permit(allowed)
    end


    def get_user
      @user = User.find(params[:id])
    end


    def check_permissions
      render_401 unless current_user.can_edit_user? @user
    end


  end
  
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  before_action :authenticate_user!
  layout "member"
end

app/views/member/pages/calendar.html.erb
<h1>Calendrier</h1>

<% if current_user.officer? %>
    <div class="page-actions">
        <%= link_to "Nouvel événement", new_member_calendar_event_path, class: "button" %>
    </div>
<% end %>


<div id='calendar'></div>

app/views/member/pages/dashboard.html.erb
<h1>Dashboard</h1>

<div class="page-actions">
    <%= link_to "Nouveau personnage", new_member_character_path, class: "button" %>
</div>

<% unless current_user.member? %>
    <div class="not-member">
        <strong>Vous n'êtes pas encore membre !</strong><br>
        Demandez à un officier de vous passer membre pour avoir accès au reste du site.
    </div>
<% end %>

<h2 class="first">Vos personnages</h2>

<% if current_user.has_character? %>
    Vous n'avez pas encore de personnage ! Créez en un pour pouvoir participer
<% end %>

<div>
    <%= render current_user.characters %>
</div>


<% if current_user.member? %>
    <h2>Evenements à venir</h2>
    <div class="dashboard-calendar-events">
        <%= render @calendar_events %>
    </div>
<% end %>

app/views/member/pages/dkp_description.html.erb
<p>A partir du 23/09/19 la guilde Stones met en place le système de points DKP (Dragon Kill Points).<br/>
Avec un solde unique de départ d’une valeur de 200 points DKP.</p>

<p>Si le principe est simple, la mise en place de ce système est perfectible, mais dans un but d’équité, il nous faut utiliser un système d’attribution des loots.
+1 dans le raid est égal à la spécialisation principale, il sera toujours prioritaire sur le +2 considéré comme une spécialisation secondaire.</p>

app/views/member/pages/roster.html.erb
<h1>Roster</h1>

<div class="page-actions">
    <%= link_to "Nouveau personnage", new_member_character_path, class: "button" %>
</div>

<%= render @characters %>