config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :member do
    get "/", to: "pages#dashboard"
    get :calendar, to: "pages#calendar"
    get :roster, to: "pages#roster"

    resources :users do
      put :stop_acting, on: :collection
      put :act_as, on: :member
    end
    
    resources :characters
    resources :calendar_events do
      get :preview, on: :member
    end

    resources :event_participations
  end

  root to: 'pages#index'

end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">

    <title>Stones</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400&display=swap" rel="stylesheet">
    <link rel="icon" type="/image/png" href="/images/favicon-16x16.png">
</head>



<body>
    <div id="wrapper">
        <div class="logo">
            <img src="/images/stones_logo01.png" alt="logo"/>
        </div>

        <nav id="nav">
            <ul>
                <li><a href="/#intro" class="scrolllink">Présentation</a></li>
                <li><a href="/#first" class="scrolllink">Recrutement</a></li>
                <li><a href="/#second" class="scrolllink">Contact</a></li>
                <li><%= link_to "Espace membre", member_path %></li>
            </ul>
        </nav>

        <div id="container">
            <%= yield %>
        </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/layouts/member.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stones</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'member', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:200,300,400&display=swap" rel="stylesheet">
    <link rel="icon" type="/image/png" href="/images/favicon-16x16.png">
  </head>

  <body>
    <div id="wrapper">


      <div id="container">
        <%= yield %>
      </div>

      <nav id="nav">
        <div class="member-logo">
          <%= link_to root_path do %>
            <%= image_tag "logo.png" %>
          <% end %>
        </div>
        <ul>
          <li><%= link_to "Dashboard", member_path %></li>
          <% if current_user.member? %>
            <li><%= link_to "Calendrier", member_calendar_path %></li>
            <li><%= link_to "Roster", member_characters_path %></li>
            <li><%= link_to "DKP", "https://docs.google.com/spreadsheets/d/15f6wKtBqHDZipibd-XpGMfrNXMGoWzDawHfCaPVQVxM/edit?usp=sharing" %></li>
          <% end %>
          <% if current_user.officer? %>
            <li><%= link_to "Membres", member_users_path %></li>
          <% end %>
          <li><%= link_to "Mon compte", edit_member_user_path(current_user.id) %> <span>(<%= link_to current_user.nickname, member_user_path(current_user.id) %>)</span></li>
          <% if current_user_acting? %>
            <li><%= link_to "Redevenir #{real_current_user.nickname}", stop_acting_member_users_path, method: :put %></li>
          <% end %>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
        </ul>
      </nav>

    </div>


    <%= javascript_include_tag 'member' %>
  </body>
</html>